"""ADR 0019 — :meth:`OpenSeesModel.build` target parity / smoke tests.

* ``build('tcl')`` matches the deck :meth:`apeSees.tcl` produces for
  the same model (per-line text equality modulo line endings).
* ``build('py')`` matches the deck :meth:`apeSees.py` produces.
* ``build('h5', out=path)`` is byte-equivalent to
  :meth:`OpenSeesModel.to_h5` and to the source archive
  (modulo ``/meta/created_iso``).
* ``build('live')`` smoke — when openseespy is importable, drives
  an in-process emitter without raising.
* ``build('aster')`` raises ``ValueError``.
* The class docstring loudly documents the tag-divergence rule
  from INV-5.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

import h5py
import numpy as np
import pytest

from apeGmsh.opensees import OpenSeesModel, apeSees
from apeGmsh.opensees.section.fiber import FiberPoint

from tests.opensees.h5._opensees_model_fixtures import (
    build_simple_frame_fem,
    build_simple_frame_h5,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _author_simple_frame_apesees() -> apeSees:
    """Return a freshly authored :class:`apeSees` instance over the
    simple-frame FEM.

    Matches the construction in
    :func:`tests.opensees.h5._opensees_model_fixtures.build_simple_frame_h5`
    so the test bed can compare ``apeSees.tcl`` against
    ``OpenSeesModel.build('tcl')`` line by line.
    """
    fem = build_simple_frame_fem()
    ops = apeSees(fem)
    ops.model(ndm=3, ndf=6)
    steel = ops.uniaxialMaterial.Steel02(fy=420e6, E=200e9, b=0.01)
    sec = ops.section.Fiber(
        GJ=1.0e9,
        fibers=(FiberPoint(material=steel, y=0.0, z=0.0, area=0.01),),
    )
    transf = ops.geomTransf.Linear(vecxz=(1.0, 0.0, 0.0))
    integ = ops.beamIntegration.Lobatto(section=sec, n_ip=5)
    ops.element.forceBeamColumn(
        pg="Cols", transf=transf, integration=integ,
    )
    return ops


# ---------------------------------------------------------------------------
# build('tcl') / build('py') parity
# ---------------------------------------------------------------------------

def test_build_tcl_matches_apesees_tcl(tmp_path: Path) -> None:
    """The deck generated by :meth:`OpenSeesModel.build('tcl')` is a
    superset (or equal set) of the lines :meth:`apeSees.tcl` produces.

    Direct byte equality is not required by ADR 0019 INV-5 — tag
    identity may diverge — but the *structure* (number of node /
    materialUniaxial / section / geomTransf / element / fix lines)
    must match.
    """
    src, _ = build_simple_frame_h5(tmp_path)
    om = OpenSeesModel.from_h5(src)
    om_tcl_text = om.build("tcl")
    assert isinstance(om_tcl_text, str)

    ops = _author_simple_frame_apesees()
    bridge_path = tmp_path / "bridge.tcl"
    ops.tcl(str(bridge_path))
    bridge_tcl_text = bridge_path.read_text(encoding="utf-8")

    om_tokens = _tcl_token_counts(om_tcl_text)
    bridge_tokens = _tcl_token_counts(bridge_tcl_text)
    # Categories the round-trip must preserve count-for-count.
    for cat in (
        "node", "uniaxialMaterial", "section", "geomTransf",
        "beamIntegration", "element", "fix",
    ):
        assert om_tokens.get(cat, 0) == bridge_tokens.get(cat, 0), (
            f"build('tcl') {cat!r} count differs from apeSees.tcl: "
            f"{om_tokens.get(cat)} vs {bridge_tokens.get(cat)}"
        )


def test_build_py_matches_apesees_py(tmp_path: Path) -> None:
    """Same parity contract as :meth:`test_build_tcl_matches_apesees_tcl`
    but on the openseespy deck."""
    src, _ = build_simple_frame_h5(tmp_path)
    om = OpenSeesModel.from_h5(src)
    om_py_text = om.build("py")
    assert isinstance(om_py_text, str)

    ops = _author_simple_frame_apesees()
    bridge_path = tmp_path / "bridge.py"
    ops.py(str(bridge_path))
    bridge_py_text = bridge_path.read_text(encoding="utf-8")

    om_tokens = _py_call_counts(om_py_text)
    bridge_tokens = _py_call_counts(bridge_py_text)
    for cat in (
        "node", "uniaxialMaterial", "section", "geomTransf",
        "beamIntegration", "element", "fix",
    ):
        assert om_tokens.get(cat, 0) == bridge_tokens.get(cat, 0), (
            f"build('py') {cat!r} count differs from apeSees.py: "
            f"{om_tokens.get(cat)} vs {bridge_tokens.get(cat)}"
        )


# ---------------------------------------------------------------------------
# build('h5')
# ---------------------------------------------------------------------------

def test_build_h5_byte_equivalent(tmp_path: Path) -> None:
    """``build('h5', out=)`` produces the same file as ``to_h5(out)``
    and matches the source (modulo ``/meta/created_iso``)."""
    src, _ = build_simple_frame_h5(tmp_path)
    om = OpenSeesModel.from_h5(src)
    out_a = tmp_path / "via_build.h5"
    out_b = tmp_path / "via_to_h5.h5"
    om.build("h5", out=out_a)
    om.to_h5(out_b)

    # via_build and via_to_h5 must agree on every group / dataset.
    with h5py.File(out_a, "r") as a, h5py.File(out_b, "r") as b:
        _assert_h5_equal(a, b)


# ---------------------------------------------------------------------------
# build('live') smoke
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    importlib.util.find_spec("openseespy") is None,
    reason="openseespy not importable",
)
def test_build_live_smoke(tmp_path: Path) -> None:
    """When openseespy is available, ``build('live')`` drives the deck
    in-process without raising.

    ADR 0019 INV-5 is documented loudly; this test only checks the
    smoke path (no tag-identity assertions).
    """
    src, _ = build_simple_frame_h5(tmp_path)
    om = OpenSeesModel.from_h5(src)
    om.build("live")


# ---------------------------------------------------------------------------
# Error paths
# ---------------------------------------------------------------------------

def test_build_unknown_target_raises(tmp_path: Path) -> None:
    src, _ = build_simple_frame_h5(tmp_path)
    om = OpenSeesModel.from_h5(src)
    with pytest.raises(ValueError, match="unknown target"):
        om.build("aster")


def test_build_h5_requires_out_kwarg(tmp_path: Path) -> None:
    src, _ = build_simple_frame_h5(tmp_path)
    om = OpenSeesModel.from_h5(src)
    with pytest.raises(TypeError, match="'out=' kwarg is required"):
        om.build("h5")


# ---------------------------------------------------------------------------
# Tag-divergence note — ADR 0019 INV-5
# ---------------------------------------------------------------------------

def test_build_live_documents_tag_divergence() -> None:
    """The class docstring loudly documents the tag-identity caveat
    from ADR 0019 INV-5.

    This isn't a runtime guard — INV-5 says tag identity *may*
    diverge; the documented caveat is the deliverable.
    """
    doc = (OpenSeesModel.__doc__ or "")
    build_doc = (OpenSeesModel.build.__doc__ or "")
    haystack = (doc + "\n" + build_doc).lower()
    assert "tag identity" in haystack
    assert "diverge" in haystack
    assert "inv-5" in haystack


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _tcl_token_counts(text: str) -> dict[str, int]:
    """Count occurrences of each leading Tcl command token.

    For lines like ``"uniaxialMaterial Steel02 1 ..."``, the leading
    token is ``"uniaxialMaterial"``.  Comment lines are skipped.
    """
    counts: dict[str, int] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        first = stripped.split(None, 1)[0]
        counts[first] = counts.get(first, 0) + 1
    return counts


def _py_call_counts(text: str) -> dict[str, int]:
    """Count occurrences of each ``ops.<call>(`` shape in a python deck."""
    counts: dict[str, int] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        # Expect e.g. ``ops.uniaxialMaterial("Steel02", 1, ...)``.
        if stripped.startswith("ops."):
            call = stripped[4:].split("(", 1)[0]
            counts[call] = counts.get(call, 0) + 1
    return counts


def _assert_h5_equal(a: h5py.File, b: h5py.File) -> None:
    """Mirror of the helper in ``test_opensees_model.py`` — kept inline
    so this test file is self-contained."""
    _assert_attrs_equal(a, b, path="/")
    _assert_group_equal(a, b, path="/")


def _assert_group_equal(a: h5py.Group, b: h5py.Group, *, path: str) -> None:
    assert sorted(a.keys()) == sorted(b.keys()), (
        f"{path}: child keys differ"
    )
    for key in sorted(a.keys()):
        a_sub = a[key]
        b_sub = b[key]
        sub_path = f"{path}{key}/"
        _assert_attrs_equal(a_sub, b_sub, path=sub_path)
        if hasattr(a_sub, "shape"):
            assert a_sub.shape == b_sub.shape, sub_path
            assert a_sub.dtype.kind == b_sub.dtype.kind, sub_path
            if a_sub.dtype.kind in ("f", "i", "u"):
                np.testing.assert_array_equal(a_sub[:], b_sub[:])
        else:
            _assert_group_equal(a_sub, b_sub, path=sub_path)


def _assert_attrs_equal(
    a: h5py.HLObject, b: h5py.HLObject, *, path: str,
) -> None:
    a_keys = {k for k in a.attrs.keys() if k != "created_iso"}
    b_keys = {k for k in b.attrs.keys() if k != "created_iso"}
    assert a_keys == b_keys, f"{path}: attr keys differ"
    for key in a_keys:
        va = a.attrs[key]
        vb = b.attrs[key]
        if isinstance(va, bytes):
            va = va.decode("utf-8")
        if isinstance(vb, bytes):
            vb = vb.decode("utf-8")
        if isinstance(va, np.ndarray) or isinstance(vb, np.ndarray):
            np.testing.assert_array_equal(np.asarray(va), np.asarray(vb))
        else:
            assert va == vb, f"{path}: attr {key!r} differs"
